name: macOS Virtualization on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Start macOS VM
        run: |
          qemu-system-x86_64 -hda macos.qcow2 -m 4G -enable-kvm
